# Generated by Django 2.1.1 on 2019-01-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patient_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgeon',
            name='hospital_name',
            field=models.CharField(choices=[('OA', 'Orthopaedics ACT'), ('CL', 'Calvary')], max_length=20),
        ),
    ]
