# Generated by Django 2.1.1 on 2019-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190131_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('0', 'Female'), ('1', 'Male'), ('2', 'Other'), ('3', 'Rather not say')], default='3', max_length=15),
        ),
    ]
