# Generated by Django 2.1.2 on 2018-11-22 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KneeMotionRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bend', models.FloatField(default=90)),
                ('stretch', models.FloatField(default=90)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PainLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('painLevel', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('isExerciseDone', models.BooleanField()),
                ('isMedicineTaken', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('operationType', models.CharField(max_length=1)),
                ('operationSide', models.CharField(max_length=1)),
                ('surgeryType', models.CharField(max_length=1)),
                ('surgeryDate', models.DateField()),
                ('dateOfBirth', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('steps', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('hospital_name', models.CharField(max_length=264)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accessrecord',
            name='name',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
        migrations.AddField(
            model_name='patient',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='first_app.Surgeon'),
        ),
        migrations.AddField(
            model_name='painlevel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient'),
        ),
        migrations.AddField(
            model_name='kneemotionrange',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient'),
        ),
    ]
