# Generated by Django 2.1.2 on 2018-11-24 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20181123_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationType', models.CharField(choices=[('K', 'Knee'), ('H', 'Hip')], default='K', max_length=1)),
                ('operationSide', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], default='L', max_length=1)),
                ('surgeryType', models.CharField(choices=[('P', 'Primary'), ('R', 'Revision')], default='P', max_length=1)),
                ('surgeryDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='kneemotionrange',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='painlevel',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operationSide',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operationType',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgeon',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgeryDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='surgeryType',
        ),
        migrations.RemoveField(
            model_name='stepcounter',
            name='patient',
        ),
        migrations.AddField(
            model_name='operation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Patient'),
        ),
        migrations.AddField(
            model_name='operation',
            name='surgeon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Surgeon'),
        ),
        migrations.AddField(
            model_name='kneemotionrange',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
        migrations.AddField(
            model_name='painlevel',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
        migrations.AddField(
            model_name='stepcounter',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
    ]
