# Generated by Django 2.1.2 on 2018-11-24 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20181124_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgeon',
            name='patients',
            field=models.ManyToManyField(through='first_app.Operation', to='first_app.Patient'),
        ),
        migrations.AlterField(
            model_name='kneemotionrange',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationSide',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('B', 'Both')], max_length=1),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operationType',
            field=models.CharField(choices=[('K', 'Knee'), ('H', 'Hip')], max_length=1),
        ),
        migrations.AlterField(
            model_name='operation',
            name='surgeryType',
            field=models.CharField(choices=[('P', 'Primary'), ('R', 'Revision')], max_length=1),
        ),
        migrations.AlterField(
            model_name='painlevel',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
        migrations.AlterField(
            model_name='stepcounter',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Operation'),
        ),
    ]
