# Generated by Django 2.1.2 on 2018-11-24 05:14

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Welcome_To_Orthoapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True)),
                ('acknowledgements', models.TextField(blank=True)),
                ('disclaimer', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Australia/Sydney'),
        ),
    ]
