# Generated by Django 2.1.2 on 2018-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_welcome_to_orthoapp_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Before_Surgery_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_admission_process', models.TextField(blank=True)),
                ('medical_tests', models.TextField(blank=True)),
                ('preparing', models.TextField(blank=True)),
                ('arranging_support', models.TextField(blank=True)),
                ('minimising_risk_of_cancellation', models.TextField(blank=True)),
                ('hospital_admission', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
