# Generated by Django 2.1.2 on 2018-11-25 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_before_surgery_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Before_Surgery_Information',
            new_name='Before_Your_Surgery',
        ),
    ]
