# Generated by Django 2.1.2 on 2018-12-08 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='kneemotionrange',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='painlevel',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='stepcounter',
            name='operation',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='KneeMotionRange',
        ),
        migrations.DeleteModel(
            name='PainLevel',
        ),
        migrations.DeleteModel(
            name='StepCounter',
        ),
    ]
