# Generated by Django 2.1.2 on 2018-12-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_page',
            name='hospital_name',
            field=models.CharField(choices=[('OA', 'Orthopaedics ACT'), ('CL', 'Calvary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='information_page',
            name='surgery_stage',
            field=models.CharField(choices=[('PRE', 'Pre Surgery'), ('PST', 'Post Surgery')], max_length=10),
        ),
    ]
