# Generated by Django 2.1.2 on 2018-12-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0002_auto_20181206_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_page',
            name='is_key_link',
            field=models.BooleanField(default=False),
        ),
    ]
