# Generated by Django 2.1.2 on 2018-12-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0003_information_page_is_key_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_page',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
