# Generated by Django 2.1.2 on 2018-12-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0004_information_page_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_page',
            name='main_text',
            field=models.TextField(blank=True),
        ),
    ]
