# Generated by Django 2.1.2 on 2018-12-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='handles_inquiry',
            field=models.BooleanField(default=False),
        ),
    ]
