# Generated by Django 2.1.2 on 2018-12-06 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_practice_handles_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='handles_inquiry',
        ),
    ]
