# Generated by Django 2.1.1 on 2019-01-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_page',
            name='surgery_stage',
            field=models.CharField(choices=[('PRE', 'Pre Surgery'), ('HOSP', 'In Hospital'), ('PST', 'Post Surgery'), ('CARE', 'Long Term Care')], max_length=20),
        ),
    ]
