# Generated by Django 2.1.1 on 2019-01-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_pages', '0002_auto_20190129_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information_page',
            name='surgery_stage',
            field=models.CharField(choices=[('PRE', 'Pre Surgery'), ('HOSP', 'In Hospital'), ('POST', 'Post Surgery'), ('CARE', 'Long Term Care')], max_length=20),
        ),
    ]
