# Generated by Django 2.1.1 on 2019-01-31 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functionality', '0003_auto_20190131_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painlevel',
            name='isExerciseDone',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
